package com.example.wordpuzzle;

public class WordsDB {



    //animal
    public static String[] animal_q1={"DRBI","OLIN","RGFO","EMSUO","EGTRI","ATC","OGD","IFSH","NWARP","OWC","TOAG","REDE","NTA","EBE","UCKD","OXF","TRA","LOW","EHN","ODAT","RKLA","GPI","RABO","LUGL","FLOW"};
    public static String[] animal_a1={"BIRD","LION","FROG","MOUSE","TIGER","CAT","DOG","FISH","PRAWN","COW","GOAT","DEER","ANT","BEE","DUCK","FOX","RAT","OWL","HEN","TOAD","LARK","PIG","BOAR","GULL","WOLF"};

    public static String[] animal_q2={"OENDYK","GFRIEFA","MYOEKN","ABRITB","POLNIHD","HATEEHC","DNAAP","LAAOK","LILARAOG","NEGINUP","RIHCTSO","PHANELET","BREAZ","AES ONIL","COAEPKC"};
    public static String[] animal_a2={"DONKEY","GIRAFFE","MONKEY","RABBIT","DOLPHIN","CHEETAH","PANDA","KOALA","GORILLA","PENGUIN","OSTRICH","ELEPHANT","ZEBRA","SEA LION","PEACOCK"};

    public static String[] animal_q3={"GLOILARTA","IPOPOPMSTUOHA","LARLIGO","ORCDCIELO","TPNLEHEA","LEONMECHA","FISHEFEUPR","MINGDRIBMHU","EHOGGDEH","TULATNARA","LEUTRT","ODMOOK GONRAD","TAMUSTPOPPIH","ROSNCEOHIR","GANOROKA"};
    public static String[] animal_a3={"ALLIGATOR","HIPPOPOTAMOUS","GORILLA","CROCODILE","ELEPHANT","CHAMELEON","PUFFERFISH","HUMMINGBIRD","HEDGEHOG","TARANTULA","SEA TURTLE","KOMODO DRAGON","HIPPOPOTAMUS","RHINOCEROS","KANGAROO"};

    //BIOLOGY

    public static String[] biology_q1={"ELLC","VUSIR","FELI","IMAANL","NGEE","OREHTY","MTOA","IUSSTE","YGOLOCE","TRIAT","NDA","SNARGO","NRA","CEO","PIDIL"};
    public static String[] biology_a1={"CELL","VIRUS","LIFE","ANIMAL","GENE","THEORY","ATOM","TISSUE","ECOLOGY","TRAIT","DNA","ORGANS","RNA","ECO","LIPID"};

    public static String[] biology_q2={"TPRINOE","CRBAAETI","THOGRW","PATLN","ONINCLG","NOMOXATY","YEMENZ","TIONPERCIL","TIONVOLEU","MISLTABOMA","NEMOORH","ILACCOLOEG","UNITYIMM","NIOTMTAU","TSIOSIM"};
    public static String[] biology_a2={"PROTEIN","BACTERIA","GROWTH","PLANT","CLONING","TAXONOMY","ENZYME","REPLICATION","EVOLUTION","METABOLISM","HORMONE","ECOLOGICAL","IMMUNITY","MUTATION","MITOSIS"};

    public static String[] biology_q3={"CSNLUEU","EOCGYLO","OSIRECMCOP","GNSOIRAM","OISLFS","TNIORSEIPA","GNAMISOROMICR","PIONTRCNATRSI","NIANTCREMBO NAD","LGOYTHONECIOB","TDIEELCOUN","TEHSSITSOPHOYN","TPYEGNOE","ENGE SXERSINOPE","TIONTFREMENA"};
    public static String[] biology_a3={"NUCLEUS","ECOLOGY","MICROSCOPE","ORGANISM","FOSSIL","RESPIRATION","MICROORGANISM","TRANSCRIPTION","RECOMBINANT DNA","BIOTECHNOLOGY","NUCLEOTIDE","PHOTOSYNTHESIS","GENOTYPE","GENE EXPRESSION","FERMENTATION"};

    //COUNTRY WORDS

    public static String[] country_q1={"IIDAN","PNISA","NJAPA","TYUKRE","PNELA","YITAL","REPU","SAU","EUA","ANIHC","XIECMO","SISAUR","QRAI","TRAAQ","NAMO"};
    public static String[] country_a1={"INDIA","SPAIN","JAPAN","TURKEY","NEPAL","ITALY","PERU","USA","UAE","CHINA","MEXICO","RUSSIA","IRAQ","QATAR","OMAN"};

    public static String[] country_q2={"ADAANC","PYETG","GMYNEAR","CRFENA","BIALZR","THOUS REOAK","ENDESW","THOUS CIAFAR","LIASUTRAA","TNAIGREAN","RIAGNIE","TMANVIE","ERGEEC","GLAURPOT","LNDAINF"};
    public static String[] country_a2={"CANADA","EGYPT","GERMANY","FRANCE","BRAZIL","SOUTH KOREA","SWEDEN","SOUTH AFRICA","AUSTRALIA","ARGENTINA","NIGERIA","VIETNAM","GREECE","PORTUGAL","FINLAND"};

    public static String[] country_q3={"IEAANTNGR","EDRLINA","NDRMAEK","RUTALPOG","MIEUBLG","LDNATSIWREZ","PNEISLPHIPI","LDNATERHNES","DIAUS RBAIAA","STNKIAPA","NDALHTIA","SNIAODNEI","WRONAY","BMOIOCLA","SYALIAMA"};
    public static String[] country_a3={"ARGENTINA","IRELAND","DENMARK","PORTUGAL","BELGIUM","SWITZERLAND","PHILIPPINES","NETHERLANDS","SAUDI ARABIA","PAKISTAN","THAILAND","INDONESIA","NORWAY","COLOMBIA","MALAYSIA"};

    //elements words

    public static String[] element_q1={"IRLESV","CRONBA","REOPCP","CINZ","NTI","RONOB","ONEN","NORAG","LUFURS","NORI","IOENDI","MUIDNI","LGDO","DAEL","DONAR","CRUYEMR"};
    public static String[] element_a1={"SILVER","CARBON","COPPER","ZINC","TIN","BORON","NEON","ARGON","SULFUR","IRON","IODINE","INDIUM","GOLD","LEAD","RADON","MERCURY"};


    public static String[] element_q2={"IMACCUL","YGNXEO","ELDA","LBOATC","IEIODN","NORI","IOENDI","MUIDNI","LGDO","DAEL","DONAR","CRUYEMR","REOPCP","CINZ","NTI"};
    public static String[] element_a2={"CALCIUM","OXYGEN","LEAD","CPBALT","IODINE","IRON","IODINE","INDIUM","GOLD","LEAD","RADON","MERCURY","COPPER","ZINC","TIN"};


    public static String[] element_q3={"LMITHUI","LAINUMPT","MSAIUOTPS","EICLKN","CHOLENIR","IRLESV","CRONBA","REOPCP","CINZ","NTI","RONOB","ONEN","NORAG","LUFURS"};
    public static String[] element_a3={"LITHIUM","PLATINUM","POTASSIUM","NICKEL","CHLORINE","SILVER","CARBON","COPPER","ZINC","TIN","BORON","NEON","ARGON","SULFUR"};

    //SPORT WORDS


    public static String[] sport_q1={"LBLA","TAB","NUR","GFLO","EOLS","ORECS","ASAP","NUKD","ETN","TIH","IKCK","LOAG","HNCUP","ULOF","PUMJ"};
    public static String[] sport_a1={"BALL","BAT","RUN","GOLF","LOSE","SCORE","PASS","DUNK","NET","HIT","KICK","GOAL","PUNCH","FOUL","JUMP"};


    public static String[] sport_q2={"WHROT","AKRTEA","ABKSLLTAEB","RYBUG","HCTCA","KECHYO","ASBALLBE","NIGLCYC","NIGLREWST","NTIONDBAM","LBETA NETNIS","ECI TNIGSKA","NIGKSI","REYCAHR","NGIXBO"};
    public static String[] sport_a2={"THROW","KARATE","BASKETBALL","RUGBY","CATCH","HOCKEY","BASEBALL","CYCLING","WRESTLING","BADMINTON","TABLE TENNIS","ICE SKATING","SKIING","ARCHERY","BOXING"};


    public static String[] sport_q3={"OPLICYMS","NEICPOOIMTT","INGGOGJ","NWMIMSGI","UJPM","ABKSLLTAEB","RYBUG","HCTCA","KECHYO","ASBALLBE","NIGLCYC","NIGLREWST","NTIONDBAM","AKRTEA","SHAQUA"};
    public static String[] sport_a3={"OLYMPICS","COMPETITION","JOGGING","SWIMMING","JUMP","BASKETBALL","RUGBY","CATCH","HOCKEY","BASEBALL","CYCLING","WRESTLING","BADMINTON","KARATE","SQUASH"};

    //Technological

    public static String[] robot_q1={"AADT","PLTPAO","EAYBDOKR","SMEUO","MORNITO","DLE","PUG","BUS","IWIF","DOEC","SO","TOB","HOCE","TREORU","KSID"};
    public static String[] robot_a1={"DATA","LAPTOP","KEYBOARD","MOUSE","MONITOR","LED","GPU","USB","WIFI","CODE","OS","BOT","ECHO","ROUTER","DISK"};


    public static String[] robot_q2={"TEFURU","OSESSNR","CINHEMA","ETCPRMUO","MROGARP","PLTPAO","EAYBDOKR","SMEUO","MORNITO","DLE","PUG","BUS","IWIF","DOEC","SO"};
    public static String[] robot_a2={"FUTURE","SENSORS","MACHINE","COMPUTER","PROGRAM","LAPTOP","KEYBOARD","MOUSE","MONITOR","LED","GPU","USB","WIFI","CODE","OS"};

    public static String[] robot_q3={"GNLYTCOHOE","IAIARIFTCL","ENEENLIICTLG","MDNOIAUH","INGNETORCOI","TEFURU","OSESSNR","CINHEMA","ETCPRMUO","MROGARP","PLTPAO","EAYBDOKR","SMEUO","MORNITO","DLE"};
    public static String[] robot_a3={"TECHNOLOGY","ARTIFICIAL","INTELLIGENCE","HUMANOID","RECOGNITION","FUTURE","SENSORS","MACHINE","COMPUTER","PROGRAM","LAPTOP","KEYBOARD","MOUSE","MONITOR","LED"};


}
